# Generated by Django 3.1.5 on 2021-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0003_auto_20210520_2240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(blank=True, to="blogging.Category"),
        ),
    ]
